name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: dugout version
      description: Output of `dugout --version`
      placeholder: "dugout 0.1.6"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS and architecture
      placeholder: "macOS 15.3 arm64 / Ubuntu 22.04 x86_64 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. dugout init --name alice
        2. dugout set KEY "value"
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error output if applicable)
    validations:
      required: true

  - type: dropdown
    id: install
    attributes:
      label: Installation method
      options:
        - cargo install
        - curl install script
        - Homebrew
        - Built from source
    validations:
      required: true
